apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-master
  labels:
    jmeter_mode: master
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: master
  template:
    metadata:
      labels:
        jmeter_mode: master
    spec:
      containers:
      - name: jmmaster
        image: <acr>/jmetermaster:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          - name: loadtest
            mountPath: /load_test
            subPath: "load_test"
          - name: azurejmeter
            mountPath: /azurejmeter
        ports:
        - containerPort: 60000
        - containerPort: 1433
      imagePullSecrets:
        - name: secret
      volumes:
      - name: loadtest 
        configMap:
         name: jmeter-load-test
      - name: azurejmeter
        persistentVolumeClaim:
          claimName: jmeter-pvc
